//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlGenerateTest.Contact
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_ApproveFlow
    {
        public int ID { get; set; }
        public int ApproveID { get; set; }
        public int UserID { get; set; }
        public int ApproveUser { get; set; }
        public string ApproveUserName { get; set; }
        public string ApproveComment { get; set; }
        public int State { get; set; }
        public System.DateTime ApproveTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public int ZMSCompanyID { get; set; }
    }
}
