//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace sqlGenerateTest.Contact
{
    using System;
    using System.Collections.Generic;
    
    public partial class oa_ApproveInfo
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public string Title { get; set; }
        public int State { get; set; }
        public string AttachmentGUID { get; set; }
        public int Type { get; set; }
        public string JsonContent { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public string Lable { get; set; }
        public int CurApproveUserID { get; set; }
        public string CurApproveUserName { get; set; }
        public string OperateLog { get; set; }
        public int ZMSCompanyID { get; set; }
    }
}
