//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContact
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LotteryEntities : baseDBContext
    {
        public LotteryEntities()
            : base("name=LotteryEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Shop_LuckAward>().Property(p => p.LuckRate).HasPrecision(18, 10);
            base.OnModelCreating(modelBuilder);
        }
    
        public DbSet<Base_UserScore> Base_UserScore { get; set; }
        public DbSet<Base_UserScoreRecord> Base_UserScoreRecord { get; set; }
        public DbSet<Base_UserScoreSource> Base_UserScoreSource { get; set; }
        public DbSet<Shop_GoodCategory> Shop_GoodCategory { get; set; }
        public DbSet<Shop_LuckAward> Shop_LuckAward { get; set; }
        public DbSet<Shop_LuckAwardStage> Shop_LuckAwardStage { get; set; }
        public DbSet<Shop_LuckDrawInfo> Shop_LuckDrawInfo { get; set; }
        public DbSet<Shop_LuckDrawRecord> Shop_LuckDrawRecord { get; set; }
        public DbSet<Shop_OrderInfo> Shop_OrderInfo { get; set; }
        public DbSet<Shop_OrderProduct> Shop_OrderProduct { get; set; }
        public DbSet<Shop_ProductInfo> Shop_ProductInfo { get; set; }
        public DbSet<Shop_ShipInfo> Shop_ShipInfo { get; set; }
    }
}
