//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_LuckDrawRecord
    {
        public int ID { get; set; }
        public int LuckID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LuckDateTime { get; set; }
        public int ProductID { get; set; }
        public int isLuck { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
