//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_LuckAward
    {
        public int ID { get; set; }
        public int LuckID { get; set; }
        public string CateCode { get; set; }
        public string ProductName { get; set; }
        public int ProductCount { get; set; }
        public int StockBalance { get; set; }
        public int isEmpty { get; set; }
        public decimal LuckRate { get; set; }
        public int ProductID { get; set; }
        public string AwardPicture { get; set; }
        public byte[] UpdateTimeStamp { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
