//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_ProductInfo
    {
        public int ID { get; set; }
        public string CateCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string ProductDetail { get; set; }
        public Nullable<decimal> ViewTimes { get; set; }
        public Nullable<decimal> Sort { get; set; }
        public Nullable<int> IsDisplay { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Weight { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Summery { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> StockBalance { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
