//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_LuckDrawInfo
    {
        public int ID { get; set; }
        public string LuckTitle { get; set; }
        public string LuckSummery { get; set; }
        public int UsedScore { get; set; }
        public int MaxTry { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int State { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
